spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/back
    username: postgres
    password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR

